# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Aivelo FTP Vault — macOS .app bundle

Usage:
    pyinstaller AiveloFTP.spec

Requirements:
    pip install pyinstaller flask paramiko pywebview cryptography

This produces:  dist/Aivelo FTP Vault.app
"""

import sys
import os

block_cipher = None

# ─── Paths ────────────────────────────────────────────────
SCRIPT = 'aivelo_ftp.py'
ICON   = 'aivelo.icns'          # macOS icon (will be generated by build.sh)

# ─── Analysis ─────────────────────────────────────────────
a = Analysis(
    [SCRIPT],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'flask',
        'flask.json',
        'flask.templating',
        'jinja2',
        'jinja2.ext',
        'markupsafe',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.debug',
        'paramiko',
        'paramiko.transport',
        'paramiko.sftp_client',
        'paramiko.rsakey',
        'paramiko.ecdsakey',
        'paramiko.ed25519key',
        'paramiko.dsskey',
        'cryptography',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.asymmetric.padding',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.serialization',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        'webview',
        'webview.platforms.cocoa',
        'objc',
        'Foundation',
        'AppKit',
        'WebKit',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'test',
        'distutils',
        'setuptools',
        'pip',
        'pkg_resources',
        'email',
        'xmlrpc',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# ─── PYZ (compressed Python modules) ─────────────────────
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ─── EXE (the binary inside the .app) ────────────────────
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AiveloFTP',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=False,                  # UPX can break macOS code signing
    console=False,              # No terminal window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,           # Build for current arch (arm64 / x86_64)
    codesign_identity=None,     # Set to your Developer ID for distribution
    entitlements_file=None,
)

# ─── COLLECT (gather all files) ──────────────────────────
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=True,
    upx=False,
    upx_exclude=[],
    name='AiveloFTP',
)

# ─── BUNDLE (the .app) ──────────────────────────────────
app = BUNDLE(
    coll,
    name='Aivelo FTP Vault.app',
    icon=ICON if os.path.exists(ICON) else None,
    bundle_identifier='nl.aivelo.ftpvault',
    version='2.1.0',
    info_plist={
        'CFBundleName':                'Aivelo FTP Vault',
        'CFBundleDisplayName':         'Aivelo FTP Vault',
        'CFBundleShortVersionString':  '2.1.0',
        'CFBundleVersion':             '2.1.0',
        'CFBundleIdentifier':          'nl.aivelo.ftpvault',
        'CFBundlePackageType':         'APPL',
        'CFBundleSignature':           'AFTP',
        'LSMinimumSystemVersion':      '11.0',
        'NSHighResolutionCapable':     True,
        'LSApplicationCategoryType':   'public.app-category.developer-tools',
        'NSAppTransportSecurity': {
            'NSAllowsArbitraryLoads': True,     # Required: connects to FTP/SFTP servers
            'NSAllowsLocalNetworking': True,    # Required: Flask runs on localhost
        },
        'NSHumanReadableCopyright':    '© 2025 Aivelo / Martijn Benders. All rights reserved.',
        # Describe why the app needs network access (for App Store / notarization)
        'NSLocalNetworkUsageDescription': 'Aivelo FTP Vault connects to FTP/SFTP servers to transfer files.',
    },
)
